### PR TITLE
Fix Issue #4 and implement working terminal scrolling

### PR DESCRIPTION
**Pull request by Herbstein**

### CODE REVIEW

**Comment by iankronquist** [comment]
@Herbstein Thanks so much! It looks like there's a slight bug in this code though. There is a line running through the middle of the screen. I turned on the timer by uncommenting line 23 in kernel/kernel.c
screen shot 2015-11-18 at 12 52 33

**Comment by Herbstein** [comment]
Fixed it. I accidentally used the horizontal coordinate when clearing the bottom line.

**Comment by Herbstein** [comment]
I would also recommend changing the function name to term_scroll. More ideally, you should change the prefix from term_<function_name> to terminal_<function_name>.

**Comment by iankronquist** [comment]
If you'd like you can make those changes as well, go ahead. They seem like good ideas.

**Comment by iankronquist** [comment]
FYI, I'm going to move a constant in terminal.c into a header which will cause merge conflicts. Sorry!

**Comment by Herbstein** [comment]
I accidentally left some code in there. Mainly the non-working backspace. Do you want that, or should it not write anything?

**Comment by iankronquist** [comment]
Sorry for letting this sit. I like all the changes! The backspace functionality is pretty neat. Thanks again. I should be now responsive after the term ends tomorrow.

**Comment by Herbstein** [comment]
No worries. I haven't been looking at any code in the mean time. Just give me a heads up if you need help with anything else!

**Comment by iankronquist** [comment]
Actually, since you asked, #10 is intimately related to this code as well. When you write past the end of the screen it page faults. I think it is writing outside of video memory by accident, maybe in the `scroll_up` function. If you're curious and have some time around the holidays, it's open.

**Comment by Herbstein** [comment]
I'll definitely look into this, thanks!

**Comment by iankronquist** [comment]
Thank you!

**Pull request merged**
